"""
Django settings for ppgec project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import re
import warnings
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or value == "":
        return default
    return int(value)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False.")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["localhost", "127.0.0.1", "0.0.0.0"])

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = env_bool("SESSION_COOKIE_HTTPONLY", True)
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", True)
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")
if env_bool("USE_X_FORWARDED_PROTO", not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

def _versao_do_arquivo():
    """Le o arquivo VERSION da raiz do projeto.

    E a fonte da verdade da versao, em desenvolvimento e em producao: a esteira
    le este mesmo arquivo e o passa como APP_VERSION na construcao da imagem
    (veja .github/workflows/build-web-image.yml).
    """
    arquivo = BASE_DIR / "VERSION"
    try:
        return arquivo.read_text(encoding="utf-8").strip() or "0.0.0"
    except OSError:
        return "0.0.0"


# Numero, com pontos, e um sufixo opcional para pre-lancamento ("1.2.0-rc.1").
# O "v" e aceito na entrada e descartado: quem exibe a versao ja escreve o "v",
# e um valor "v1.0.0" renderizaria "vv1.0.0".
_FORMATO_VERSAO = re.compile(r"^v?\d+(?:\.\d+)*(?:[-+][0-9A-Za-z.-]+)?$")


def _versao_publicada():
    """A versao exibida ao usuario, vinda do ambiente ou do arquivo.

    APP_VERSION so e aceito se tiver forma de versao. Ja aconteceu de a esteira
    passar ali o nome do branch que disparou o build -- todo merge em main
    produzia APP_VERSION="main", e o rodape de todas as telas exibia "vmain".

    A esteira foi corrigida para ler o arquivo VERSION, entao este filtro nao e
    o conserto: e a garantia de que um erro de configuracao volte a degradar
    para a versao do repositorio, em vez de escrever qualquer texto no lugar
    onde o usuario espera uma versao.

    O aviso existe para o caso nao ser silencioso: um valor descartado sem
    rastro e um problema que ninguem descobre.
    """
    do_ambiente = (os.getenv("APP_VERSION") or "").strip()
    if not do_ambiente:
        return _versao_do_arquivo()

    if _FORMATO_VERSAO.match(do_ambiente):
        return do_ambiente.lstrip("v")

    do_arquivo = _versao_do_arquivo()
    warnings.warn(
        f"APP_VERSION={do_ambiente!r} nao tem forma de versao e foi ignorado; "
        f"exibindo {do_arquivo!r}, do arquivo VERSION.",
        RuntimeWarning,
        stacklevel=2,
    )
    return do_arquivo


APP_VERSION = _versao_publicada()
APP_REVISION = os.getenv("APP_REVISION", "unknown")
APP_BUILD_RUN_ID = os.getenv("APP_BUILD_RUN_ID", "local")

# Exibido no rodape de todas as telas.
APP_ORGANIZACAO = "PPGEC · UPE"
APP_COPYRIGHT = "Todos os direitos reservados ao PPGEC · UPE"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'processos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ppgec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ppgec.context_processors.rodape_institucional',
                'processos.context_processors.processos_atrasados',
                'processos.context_processors.navegacao_lateral',
            ],
        },
    },
]

WSGI_APPLICATION = 'ppgec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if env_bool("USE_POSTGRES", bool(os.getenv("POSTGRES_DB"))):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "ppgec"),
            "USER": os.getenv("POSTGRES_USER", "ppgec"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Nome dos arquivos estaticos com hash do conteudo (app.a1b2c3d4.css).
#
# Sem isso o CSS era servido sempre como /static/css/app.css: o navegador
# guardava a versao antiga e continuava usando depois do deploy, misturando
# marcacao nova com estilo velho. Com o hash, qualquer alteracao gera uma URL
# nova e o cache nunca fica desatualizado.
#
# O WhiteNoise complementa: serve os arquivos com hash como imutaveis por um
# ano e mantem prazo curto nos demais. Tambem gera versoes comprimidas.
#
# Em DEBUG=True o Django ignora o hash e serve o caminho direto, entao o
# desenvolvimento nao depende de rodar collectstatic a cada alteracao.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "ppgec.storage.EstaticosComHash",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

# --------------------------------------------------------------------------
# Armazenamento dos documentos enviados
#
# Sem AWS_STORAGE_BUCKET_NAME, os arquivos ficam em disco (MEDIA_ROOT) -- e o
# modo de desenvolvimento. Com o nome do bucket definido, passam para o S3.
#
# A escolha e pela presenca do bucket, e nao por um booleano separado, para nao
# existir o estado "S3 ligado, bucket nao informado": ou ha destino, ou nao ha.
# --------------------------------------------------------------------------
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "").strip()
USA_S3 = bool(AWS_STORAGE_BUCKET_NAME)

if USA_S3:
    from ppgec.storage import configuracao_s3

    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "").strip()
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "").strip()
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1").strip()

    # Vida da URL assinada, em segundos. Curta de proposito: a URL e entregue
    # depois da verificacao de permissao e, a partir dai, vale por si -- quanto
    # menos durar, menor a janela em que um link repassado ainda abre.
    AWS_QUERYSTRING_EXPIRE = int(os.getenv("AWS_QUERYSTRING_EXPIRE", "300"))

    STORAGES["default"] = configuracao_s3(
        bucket=AWS_STORAGE_BUCKET_NAME,
        regiao=AWS_S3_REGION_NAME,
        chave=AWS_ACCESS_KEY_ID,
        segredo=AWS_SECRET_ACCESS_KEY,
        expiracao_da_url=AWS_QUERYSTRING_EXPIRE,
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'processos.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Encerra o login após 20 minutos sem uma requisição autenticada. Ao salvar a
# sessão em cada requisição, o prazo é renovado enquanto o usuário está ativo.
SESSION_COOKIE_AGE = 20 * 60
SESSION_SAVE_EVERY_REQUEST = True

# email config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = f"AcadFlow <{EMAIL_HOST_USER}>"

SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "acadflow.password_reset": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# celery config
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
#CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0") (tirar comentario dessa linha)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# django-celery-results
INSTALLED_APPS += ["django_celery_results"]
