# Generated by Django 5.2.8 on 2026-04-06 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APROVEITAMENTO_CREDITOS', 'Aproveitamento de Creditos'), ('DISPENSA_DISCIPLINA', 'Dispensa de Disciplina'), ('TRANCAMENTO_MATRICULA', 'Trancamento de Matricula'), ('PRORROGACAO_PRAZO', 'Prorrogacao de Prazo'), ('REINGRESSO', 'Reingresso'), ('MUDANCA_ORIENTADOR', 'Mudanca de Orientador'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('RECURSO', 'Recurso'), ('OUTRO', 'Outro')], max_length=40)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status_inicial', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], max_length=25, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=25)),
                ('prioridade', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10, null=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_internas', models.TextField(blank=True)),
                ('setor_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_atuais', to='processos.setor')),
                ('usuario_criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/processos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('REQUERIMENTO', 'Requerimento'), ('PARECER', 'Parecer'), ('ATA', 'Ata'), ('COMPROVANTE', 'Comprovante'), ('OUTRO', 'Outro')], max_length=20)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='TramitacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('status_resultante', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], max_length=25, null=True)),
                ('data_encaminhamento', models.DateTimeField(auto_now_add=True)),
                ('encaminhado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='processos.processo')),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_destino', to='processos.setor')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_origem', to='processos.setor')),
            ],
            options={
                'ordering': ['-data_encaminhamento'],
            },
        ),
    ]
