# Generated by Django 5.2.8 on 2026-04-24 13:18

from django.contrib.auth.hashers import make_password
from django.db import migrations


MOCK_DOCENTE_EMAIL = "mock.docente@ppgec.local"
MOCK_SERVIDOR_EMAIL = "mock.servidor@ppgec.local"
MOCK_ALUNOS_EMAILS = [
    "mock.aluno1@ppgec.local",
    "mock.aluno2@ppgec.local",
]
MOCK_PROCESSO_NUMEROS = [
    "202604-900001",
    "202604-900002",
    "202604-900003",
]
MOCK_SETOR_NOMES = [
    "Secretaria PPGEC",
    "Coordenacao PPGEC",
    "Colegiado PPGEC",
]


def seed_mock_data(apps, schema_editor):
    User = apps.get_model("processos", "User")
    Docente = apps.get_model("processos", "Docente")
    Aluno = apps.get_model("processos", "Aluno")
    Setor = apps.get_model("processos", "Setor")
    Processo = apps.get_model("processos", "Processo")

    setor_secretaria, _ = Setor.objects.update_or_create(
        nome=MOCK_SETOR_NOMES[0],
        defaults={"descricao": "[MOCK] Recepcao de processos", "ativo": True},
    )
    setor_coordenacao, _ = Setor.objects.update_or_create(
        nome=MOCK_SETOR_NOMES[1],
        defaults={"descricao": "[MOCK] Analise e despacho", "ativo": True},
    )
    Setor.objects.update_or_create(
        nome=MOCK_SETOR_NOMES[2],
        defaults={"descricao": "[MOCK] Deliberacao colegiada", "ativo": True},
    )

    docente, _ = Docente.objects.update_or_create(
        email=MOCK_DOCENTE_EMAIL,
        defaults={
            "nome": "Docente Mock",
            "tipo_usuario": "DOCENTE",
            "password": make_password("123456"),
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
            "externo": False,
            "permanente": True,
            "coordenador": False,
        },
    )

    aluno_1, _ = Aluno.objects.update_or_create(
        email=MOCK_ALUNOS_EMAILS[0],
        defaults={
            "nome": "Aluno Mock 1",
            "tipo_usuario": "ALUNO",
            "password": make_password("123456"),
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
            "ingresso": "2024-03-01",
            "matricula": "2024A0001",
            "orientador_id": docente.id,
        },
    )
    aluno_2, _ = Aluno.objects.update_or_create(
        email=MOCK_ALUNOS_EMAILS[1],
        defaults={
            "nome": "Aluno Mock 2",
            "tipo_usuario": "ALUNO",
            "password": make_password("123456"),
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
            "ingresso": "2025-03-01",
            "matricula": "2025A0002",
            "orientador_id": docente.id,
        },
    )

    servidor, _ = User.objects.update_or_create(
        email=MOCK_SERVIDOR_EMAIL,
        defaults={
            "nome": "Servidor Mock",
            "tipo_usuario": "SERVIDOR",
            "password": make_password("123456"),
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
        },
    )

    Processo.objects.update_or_create(
        numero=MOCK_PROCESSO_NUMEROS[0],
        defaults={
            "usuario_criado_por_id": aluno_1.id,
            "tipo": "PRORROGACAO_PRAZO",
            "assunto": "Prorrogacao de prazo para defesa",
            "descricao": "[MOCK] Solicitacao de prorrogacao por 6 meses.",
            "status_inicial": "ABERTO",
            "status": "EM_ANALISE",
            "prioridade": "MEDIA",
            "setor_atual_id": setor_coordenacao.id,
            "observacoes_internas": "[MOCK] Aguardando parecer do orientador.",
        },
    )
    Processo.objects.update_or_create(
        numero=MOCK_PROCESSO_NUMEROS[1],
        defaults={
            "usuario_criado_por_id": aluno_2.id,
            "tipo": "APROVEITAMENTO_CREDITOS",
            "assunto": "Aproveitamento de creditos externos",
            "descricao": "[MOCK] Pedido de aproveitamento de disciplinas cursadas.",
            "status_inicial": "ABERTO",
            "status": "AGUARDANDO_DOCUMENTO",
            "prioridade": "BAIXA",
            "setor_atual_id": setor_secretaria.id,
            "observacoes_internas": "[MOCK] Falta anexar historico autenticado.",
        },
    )
    Processo.objects.update_or_create(
        numero=MOCK_PROCESSO_NUMEROS[2],
        defaults={
            "usuario_criado_por_id": servidor.id,
            "tipo": "OUTRO",
            "assunto": "Atualizacao de fluxo interno",
            "descricao": "[MOCK] Ajuste de tramitacao para validacao do sistema.",
            "status_inicial": "ABERTO",
            "status": "ENCAMINHADO",
            "prioridade": "ALTA",
            "setor_atual_id": setor_coordenacao.id,
            "observacoes_internas": "[MOCK] Em piloto para homologacao.",
        },
    )


def remove_mock_data(apps, schema_editor):
    User = apps.get_model("processos", "User")
    Docente = apps.get_model("processos", "Docente")
    Aluno = apps.get_model("processos", "Aluno")
    Setor = apps.get_model("processos", "Setor")
    Processo = apps.get_model("processos", "Processo")

    Processo.objects.filter(numero__in=MOCK_PROCESSO_NUMEROS).delete()
    Aluno.objects.filter(email__in=MOCK_ALUNOS_EMAILS).delete()
    Docente.objects.filter(email=MOCK_DOCENTE_EMAIL).delete()
    User.objects.filter(email=MOCK_SERVIDOR_EMAIL).delete()
    Setor.objects.filter(nome__in=MOCK_SETOR_NOMES, descricao__startswith="[MOCK]").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processo_documento_tramitacaoprocesso'),
    ]

    operations = [
        migrations.RunPython(seed_mock_data, remove_mock_data),
    ]
