# Generated by Django 5.2.8 on 2026-04-24 13:43

from django.db import migrations


TARGET_SETORES = [
    ("Requerente", "Setor de abertura do processo pelo solicitante."),
    ("Secretaria PPGEC", "Recepcao e triagem administrativa."),
    ("Coordenação PPG", "Analise e despacho da coordenacao."),
    ("Colegiando PPGEC (Pleno)", "Deliberacoes do colegiado pleno."),
]

ALIASES = {
    "Requerente": ["Requerente", "Secretaria"],
    "Secretaria PPGEC": ["Secretaria PPGEC"],
    "Coordenação PPG": ["Coordenação PPG", "Coordenacao PPG", "Coordenacao PPGEC"],
    "Colegiando PPGEC (Pleno)": [
        "Colegiando PPGEC (Pleno)",
        "Colegiado PPGEC",
        "Colegiado PPGEC (Pleno)",
    ],
}


def _repoint_setor_refs(Setor, Processo, TramitacaoProcesso, source_setor, target_setor):
    if source_setor.id == target_setor.id:
        return

    Processo.objects.filter(setor_atual_id=source_setor.id).update(setor_atual_id=target_setor.id)
    TramitacaoProcesso.objects.filter(setor_destino_id=source_setor.id).update(
        setor_destino_id=target_setor.id
    )
    TramitacaoProcesso.objects.filter(setor_origem_id=source_setor.id).update(
        setor_origem_id=target_setor.id
    )
    source_setor.delete()


def forward_normalize_setores(apps, schema_editor):
    Setor = apps.get_model("processos", "Setor")
    Processo = apps.get_model("processos", "Processo")
    TramitacaoProcesso = apps.get_model("processos", "TramitacaoProcesso")

    target_by_name = {}
    for nome, descricao in TARGET_SETORES:
        setor, _ = Setor.objects.get_or_create(nome=nome, defaults={"descricao": descricao, "ativo": True})
        setor.descricao = descricao
        setor.ativo = True
        setor.save(update_fields=["descricao", "ativo"])
        target_by_name[nome] = setor

    for target_name, alias_names in ALIASES.items():
        target_setor = target_by_name[target_name]
        alias_setores = Setor.objects.filter(nome__in=alias_names).exclude(id=target_setor.id)
        for source_setor in alias_setores:
            _repoint_setor_refs(Setor, Processo, TramitacaoProcesso, source_setor, target_setor)

    default_setor = target_by_name["Secretaria PPGEC"]
    extras = Setor.objects.exclude(nome__in=[nome for nome, _ in TARGET_SETORES]).exclude(id=default_setor.id)
    for extra in extras:
        _repoint_setor_refs(Setor, Processo, TramitacaoProcesso, extra, default_setor)


def backward_noop(apps, schema_editor):
    # Sem reversao automatica para evitar perder consolidacao de referencias.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_seed_mock_data'),
    ]

    operations = [
        migrations.RunPython(forward_normalize_setores, backward_noop),
    ]
