# Generated by Django 5.2.8 on 2026-04-24 13:45

from django.db import migrations


TARGET_SETORES = [
    ("Requerente", "Setor de abertura do processo pelo solicitante."),
    ("Secretaria PPGEC", "Recepcao e triagem administrativa."),
    ("Coordenação PPG", "Analise e despacho da coordenacao."),
    ("Colegiando PPGEC (Pleno)", "Deliberacoes do colegiado pleno."),
]

RENAME_ALIASES = {
    "Requerente": ["Secretaria", "Requerente"],
    "Secretaria PPGEC": ["Secretaria PPGEC"],
    "Coordenação PPG": ["Coordenacao PPGEC", "Coordenacao PPG", "Coordenação PPG"],
    "Colegiando PPGEC (Pleno)": [
        "Colegiado PPGEC",
        "Colegiado PPGEC (Pleno)",
        "Colegiando PPGEC (Pleno)",
    ],
}


def _repoint_setor_refs(Processo, TramitacaoProcesso, source_setor_id, target_setor_id):
    if source_setor_id == target_setor_id:
        return

    Processo.objects.filter(setor_atual_id=source_setor_id).update(setor_atual_id=target_setor_id)
    TramitacaoProcesso.objects.filter(setor_destino_id=source_setor_id).update(setor_destino_id=target_setor_id)
    TramitacaoProcesso.objects.filter(setor_origem_id=source_setor_id).update(setor_origem_id=target_setor_id)


def forward_enforce_setores(apps, schema_editor):
    Setor = apps.get_model("processos", "Setor")
    Processo = apps.get_model("processos", "Processo")
    TramitacaoProcesso = apps.get_model("processos", "TramitacaoProcesso")

    target_ids = {}
    for nome, descricao in TARGET_SETORES:
        aliases = RENAME_ALIASES.get(nome, [nome])
        setor = Setor.objects.filter(nome__in=aliases).order_by("id").first()
        if setor:
            setor.nome = nome
            setor.descricao = descricao
            setor.ativo = True
            setor.save(update_fields=["nome", "descricao", "ativo"])
        else:
            setor = Setor.objects.create(nome=nome, descricao=descricao, ativo=True)
        target_ids[nome] = setor.id

    for nome, aliases in RENAME_ALIASES.items():
        target_id = target_ids[nome]
        extras_mesmo_grupo = Setor.objects.filter(nome__in=aliases).exclude(id=target_id)
        for extra in extras_mesmo_grupo:
            _repoint_setor_refs(Processo, TramitacaoProcesso, extra.id, target_id)
            extra.delete()

    default_id = target_ids["Secretaria PPGEC"]
    all_target_names = [nome for nome, _ in TARGET_SETORES]
    extras = Setor.objects.exclude(nome__in=all_target_names).exclude(id=default_id)
    for extra in extras:
        _repoint_setor_refs(Processo, TramitacaoProcesso, extra.id, default_id)
        extra.delete()


def backward_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_normalize_setores'),
    ]

    operations = [
        migrations.RunPython(forward_enforce_setores, backward_noop),
    ]
