# Generated by Django 5.2.8 on 2026-04-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_enforce_setores_oficiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo_removido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_removido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo_removido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_com_arquivo_removido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='restrito',
            field=models.BooleanField(default=False),
        ),
    ]
