# Generated by Django 5.2.8 on 2026-04-24 14:27

from django.db import migrations, models


def forward_fill_restricao_tipo(apps, schema_editor):
    Documento = apps.get_model("processos", "Documento")
    Documento.objects.filter(restrito=True).update(
        restricao_tipo="OUTRO",
        restricao_outro="Migrado de classificacao anterior (restrito=True).",
    )


def backward_fill_restricao_tipo(apps, schema_editor):
    Documento = apps.get_model("processos", "Documento")
    Documento.objects.filter(restricao_tipo="OUTRO").update(restricao_tipo="NAO", restricao_outro="")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_documento_arquivo_removido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='restricao_outro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='restricao_tipo',
            field=models.CharField(choices=[('NAO', 'Não'), ('INFORMACAO_PESSOAL', 'Informação pessoal (Art. 31 da Lei de Acesso à Informação (Lei nº 12.527/2011))'), ('DOCUMENTO_PREPARATORIO', 'Documento preparatório / processo decisório (Art. 7º, §3º da Lei de Acesso à Informação (Lei nº 12.527/2011))'), ('INVESTIGACAO_ADMINISTRATIVA', 'Investigação ou apuração administrativa (Art. 150 da Lei nº 8.112/1990)'), ('SIGILO_ACADEMICO', 'Sigilo acadêmico (avaliações, pareceres, bancas) (Art. 31 da Lei de Acesso à Informação (Lei nº 12.527/2011))'), ('PROPRIEDADE_INTELECTUAL', 'Propriedade intelectual / direito autoral (Art. 24, III da Lei nº 9.610/1998; Art. 2º da Lei nº 9.609/1998)'), ('SEGREDO_INDUSTRIAL', 'Segredo industrial ou informação estratégica (Art. 195, XIV da Lei nº 9.279/1996)'), ('SIGILO_LEGAL_ESPECIFICO', 'Sigilo legal específico (fiscal, bancário, etc.) (Art. 198 do CTN; LC nº 105/2001)'), ('OUTRO', 'Outro (especificar)')], default='NAO', max_length=40),
        ),
        migrations.RunPython(forward_fill_restricao_tipo, backward_fill_restricao_tipo),
    ]
