# Generated by Django 5.2.8 on 2026-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_alter_documento_restricao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo_removido_motivo',
            field=models.TextField(blank=True),
        ),
    ]
