# Generated by Django 5.2.8 on 2026-04-24 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_documento_arquivo_removido_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonimo', models.BooleanField(default=False)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_processo', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='processos.processo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
