# Generated by Django 5.2.8 on 2026-04-24 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_comentarioprocesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CIENTE_ORIENTADOR', 'Ciente do orientador')], max_length=40)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CIENTE', 'Ciente'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('mensagem_solicitacao', models.TextField(blank=True)),
                ('mensagem_manifestacao', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_manifestacao', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes', to='processos.processo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_pendentes', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestacoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
