# Generated by Django 5.2.8 on 2026-04-24 18:25

from django.db import migrations, models


def normalizar_status_para_em_analise(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    Processo.objects.filter(status="ABERTO").update(status="EM_ANALISE")
    Processo.objects.filter(status_inicial="ABERTO").update(status_inicial="EM_ANALISE")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_manifestacaoprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='termo_finalizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='EM_ANALISE', max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_inicial',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacaoprocesso',
            name='status_resultante',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('ENCAMINHADO', 'Encaminhado'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], max_length=25, null=True),
        ),
        migrations.RunPython(normalizar_status_para_em_analise, migrations.RunPython.noop),
    ]
