# Generated by Django 5.2.8 on 2026-04-24 18:34

from django.db import migrations, models
from django.db.models import F


def normalizar_status_legados(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    TramitacaoProcesso = apps.get_model("processos", "TramitacaoProcesso")

    Processo.objects.filter(status__in=["ABERTO", "ENCAMINHADO"]).update(status="EM_ANALISE")
    Processo.objects.filter(status_inicial__in=["ABERTO", "ENCAMINHADO"]).update(
        status_inicial="EM_ANALISE"
    )
    Processo.objects.filter(status__in=["DEFERIDO", "INDEFERIDO", "ARQUIVADO"]).update(
        status="FINALIZADO"
    )
    Processo.objects.filter(
        status="FINALIZADO",
        finalizado_em__isnull=True,
    ).update(finalizado_em=F("atualizado_em"))
    Processo.objects.filter(status_inicial__in=["DEFERIDO", "INDEFERIDO", "ARQUIVADO"]).update(
        status_inicial="FINALIZADO"
    )

    TramitacaoProcesso.objects.filter(status_resultante__in=["ABERTO", "ENCAMINHADO"]).update(
        status_resultante="EM_ANALISE"
    )
    TramitacaoProcesso.objects.filter(
        status_resultante__in=["DEFERIDO", "INDEFERIDO", "ARQUIVADO"]
    ).update(status_resultante="FINALIZADO")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_processo_termo_finalizacao_alter_processo_status_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_status_legados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('FINALIZADO', 'Finalizado')], default='EM_ANALISE', max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_inicial',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacaoprocesso',
            name='status_resultante',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
    ]
