# Generated by Django 5.2.8 on 2026-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_alter_processo_status_alter_processo_status_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='isQualificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='prazo_defesa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='prazo_qualificacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
