# Generated by Django 5.2.8 on 2026-04-27 17:59

import django.core.validators
from django.db import migrations, models


def _to_semestre(value):
    if value in (None, ""):
        return value

    if hasattr(value, "year") and hasattr(value, "month"):
        semestre = 1 if value.month <= 6 else 2
        return f"{value.year}.{semestre}"

    raw = str(value).strip()
    if not raw:
        return raw
    if len(raw) == 6 and raw[4] == "." and raw[-1] in {"1", "2"}:
        return raw

    if len(raw) >= 7 and raw[4] == "-":
        year = raw[:4]
        month_str = raw[5:7]
        if year.isdigit() and month_str.isdigit():
            semestre = 1 if int(month_str) <= 6 else 2
            return f"{year}.{semestre}"
    return raw


def normalizar_semestres_aluno(apps, schema_editor):
    Aluno = apps.get_model("processos", "Aluno")
    for aluno in Aluno.objects.all().only("id", "ingresso", "prazo_defesa", "prazo_qualificacao"):
        ingresso = _to_semestre(aluno.ingresso)
        prazo_defesa = _to_semestre(aluno.prazo_defesa)
        prazo_qualificacao = _to_semestre(aluno.prazo_qualificacao)
        updates = {}
        if ingresso != aluno.ingresso:
            updates["ingresso"] = ingresso
        if prazo_defesa != aluno.prazo_defesa:
            updates["prazo_defesa"] = prazo_defesa
        if prazo_qualificacao != aluno.prazo_qualificacao:
            updates["prazo_qualificacao"] = prazo_qualificacao
        if updates:
            Aluno.objects.filter(pk=aluno.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_aluno_isqualificado_aluno_prazo_defesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ingresso',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='prazo_defesa',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='prazo_qualificacao',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')]),
        ),
        migrations.RunPython(normalizar_semestres_aluno, migrations.RunPython.noop),
    ]
