# Generated by Django 5.2.8 on 2026-04-28 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def popular_status_aluno_com_base_em_is_active(apps, schema_editor):
    Aluno = apps.get_model("processos", "Aluno")
    Aluno.objects.filter(is_active=False).update(status_aluno="DESLIGADO")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_alter_aluno_ingresso_alter_aluno_prazo_defesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_defesa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='deposito_versao_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_defesa',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DESLIGADO', 'Desligado'), ('DEFENDEU', 'Defendeu')], default='ATIVO', max_length=12),
        ),
        migrations.RunPython(popular_status_aluno_com_base_em_is_active, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AlteracaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Deposito versao final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificacao'), ('PRAZO_DEFESA', 'Prazo defesa')], max_length=25)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_alunos_realizadas', to=settings.AUTH_USER_MODEL)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='processos.aluno')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
