# Generated by Django 5.2 on 2026-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0018_remove_processo_prioridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="tipo",
            field=models.CharField(
                choices=[
                    (
                        "APROVEITAMENTO_DISPENSA_CREDITOS",
                        "Aproveitamento de Créditos ou Dispensa de Disciplina",
                    ),
                    ("DEFESA_MESTRADO", "Defesa de Mestrado"),
                    ("DEFESA_DOUTORADO", "Defesa de Doutorado"),
                    ("QUALIFICACAO_DOUTORADO", "Qualificação de Doutorado"),
                    ("TRANCAMENTO_MATRICULA", "Trancamento de Matrícula"),
                    ("PRORROGACAO_PRAZO", "Prorrogação de Prazo"),
                    ("REINGRESSO", "Reingresso"),
                    ("MUDANCA_ORIENTADOR", "Mudança de Orientador(a)"),
                    ("OUTRO", "Outro"),
                ],
                max_length=40,
            ),
        ),
    ]
