# Generated by Django 5.2 on 2026-05-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0019_alter_processo_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="coorientador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo_usuario": "DOCENTE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coorientandos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coorientador_externo_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coorientador_externo_instituicao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="aluno",
            name="coorientador_externo_nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
