# Generated by Django 5.2 on 2026-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_alter_alteracaoaluno_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nivel_curso',
            field=models.CharField(choices=[('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], default='MESTRADO', max_length=10),
        ),
    ]
