# Generated by Django 5.2 on 2026-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0022_aluno_nivel_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='reingressante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Deposito versao final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificacao'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso')], max_length=25),
        ),
    ]
