# Generated by Django 5.2 on 2026-05-06 14:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_trajetorias_iniciais(apps, schema_editor):
    Aluno = apps.get_model("processos", "Aluno")
    TrajetoriaAcademica = apps.get_model("processos", "TrajetoriaAcademica")

    for aluno in Aluno.objects.all().iterator():
        if TrajetoriaAcademica.objects.filter(aluno=aluno).exists():
            continue

        status = "ATIVA"
        if aluno.status_aluno == "DEFENDEU":
            status = "CONCLUIDA"
        elif aluno.status_aluno == "DESLIGADO":
            status = "DESLIGADA"

        TrajetoriaAcademica.objects.create(
            aluno=aluno,
            nivel_curso=aluno.nivel_curso,
            status=status,
            ingresso=aluno.ingresso,
            prazo_qualificacao=aluno.prazo_qualificacao or "",
            prazo_defesa=aluno.prazo_defesa or "",
            orientador_id=aluno.orientador_id,
            coorientador_id=aluno.coorientador_id,
            coorientador_externo_nome=aluno.coorientador_externo_nome,
            coorientador_externo_email=aluno.coorientador_externo_email,
            coorientador_externo_instituicao=aluno.coorientador_externo_instituicao,
            numero_defesa=aluno.numero_defesa,
            data_defesa=aluno.data_defesa,
            deposito_versao_final=aluno.deposito_versao_final,
            reingressante=aluno.reingressante,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_aluno_reingressante_alter_alteracaoaluno_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Deposito versao final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificacao'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso'), ('TRAJETORIA', 'Trajetoria academica')], max_length=25),
        ),
        migrations.CreateModel(
            name='TrajetoriaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_curso', models.CharField(choices=[('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=10)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluida'), ('DESLIGADA', 'Desligada')], default='ATIVA', max_length=15)),
                ('ingresso', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')])),
                ('prazo_qualificacao', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')])),
                ('prazo_defesa', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')])),
                ('coorientador_externo_nome', models.CharField(blank=True, max_length=255)),
                ('coorientador_externo_email', models.EmailField(blank=True, max_length=254)),
                ('coorientador_externo_instituicao', models.CharField(blank=True, max_length=255)),
                ('numero_defesa', models.CharField(blank=True, max_length=80)),
                ('data_defesa', models.DateField(blank=True, null=True)),
                ('deposito_versao_final', models.BooleanField(default=False)),
                ('reingressante', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajetorias', to='processos.aluno')),
                ('coorientador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajetorias_coorientadas', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajetorias_orientadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RunPython(criar_trajetorias_iniciais, migrations.RunPython.noop),
    ]
