# Generated by Django 5.2 on 2026-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0024_alter_alteracaoaluno_tipo_trajetoriaacademica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='coorientador',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='coorientador_externo_email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='coorientador_externo_instituicao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='coorientador_externo_nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_defesa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='deposito_versao_final',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ingresso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='isQualificado',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nivel_curso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='numero_defesa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='orientador',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='prazo_defesa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='prazo_qualificacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='reingressante',
        ),
        migrations.AddField(
            model_name='trajetoriaacademica',
            name='isQualificado',
            field=models.BooleanField(default=False),
        ),
    ]
