# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0025_remove_aluno_coorientador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajetoriaacademica",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("CONCLUIDA", "Concluida"),
                    ("DESLIGADA", "Desligada"),
                    ("TRANCADA", "Trancado"),
                ],
                default="ATIVA",
                max_length=15,
            ),
        ),
    ]
