# Generated by Django 5.2 on 2026-06-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0026_alter_trajetoriaacademica_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail institucional do setor', max_length=255, null=True),
        ),
    ]
