# Generated by Django 5.2 on 2026-05-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0026_alter_trajetoriaacademica_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail institucional do setor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('APROVEITAMENTO_DISPENSA_CREDITOS', 'Aproveitamento de Créditos ou Dispensa de Disciplina'), ('DEFESA_MESTRADO', 'Defesa de Mestrado'), ('DEFESA_DOUTORADO', 'Defesa de Doutorado'), ('QUALIFICACAO_DOUTORADO', 'Qualificação de Doutorado'), ('ESTAGIO_DOCENCIA', 'Estágio docência'), ('TRANCAMENTO_MATRICULA', 'Trancamento de Matrícula'), ('PRORROGACAO_PRAZO', 'Prorrogação de Prazo'), ('REINGRESSO', 'Reingresso'), ('MUDANCA_ORIENTADOR', 'Mudança de Orientador(a)'), ('OUTRO', 'Outro')], max_length=40),
        ),
    ]
