# Generated by Django 5.2 on 2026-05-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0027_setor_email_alter_processo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstagioDocencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('dispensado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagios_docencia', to='processos.aluno')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estagios_supervisionados', to='processos.docente')),
            ],
            options={
                'ordering': ['aluno'],
            },
        ),
    ]
