# Generated by Django 5.2 on 2026-06-05 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0027_setor_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Polo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="polo_atuacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servidores",
                to="processos.polo",
            ),
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("capacidade", models.PositiveIntegerField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "polo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salas",
                        to="processos.polo",
                    ),
                ),
            ],
            options={
                "ordering": ["polo__nome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ReservaAmbiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AULA", "Aula"),
                            ("DEFESA", "Defesa"),
                            ("REUNIAO_PESQUISA", "Reuniao de pesquisa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                ("recorrente", models.BooleanField(default=False)),
                (
                    "grupo_recorrencia",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "DOCENTE"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_docente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="processos.sala",
                    ),
                ),
            ],
            options={
                "ordering": ["inicio", "sala__nome"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadeSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terca-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sabado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="processos.sala",
                    ),
                ),
            ],
            options={
                "ordering": ["sala", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.AddConstraint(
            model_name="sala",
            constraint=models.UniqueConstraint(
                fields=("polo", "nome"), name="unique_sala_por_polo"
            ),
        ),
    ]
