# Generated by Django 5.2 on 2026-06-02 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0028_estagiodocencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estagiodocencia',
            options={'ordering': ['trajetoria'], 'verbose_name': 'Estágio de Docência', 'verbose_name_plural': 'Estágios de Docência'},
        ),
        migrations.RemoveField(
            model_name='estagiodocencia',
            name='aluno',
        ),
        migrations.AddField(
            model_name='estagiodocencia',
            name='orientador_ciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estagiodocencia',
            name='processo_vinculado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagio_gerado', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='estagiodocencia',
            name='relatorio_entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estagiodocencia',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('AGUARDANDO', 'Aguardando Aprovação'), ('ANDAMENTO', 'Em Andamento'), ('PENDENTE', 'Pendente de Relatório'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=15),
        ),
        migrations.AddField(
            model_name='estagiodocencia',
            name='trajetoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estagios_docencia', to='processos.trajetoriaacademica'),
            preserve_default=False,
        ),
    ]
