# Generated by Django 5.2 on 2026-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_seed_polo_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], default='EM_ANALISE', max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_inicial',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacaoprocesso',
            name='status_resultante',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em analise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciencia'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
    ]
