# Generated by Django 5.2 on 2026-06-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0029_alter_estagiodocencia_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiodocencia',
            name='dispensado',
        ),
        migrations.RemoveField(
            model_name='estagiodocencia',
            name='orientador_ciente',
        ),
        migrations.RemoveField(
            model_name='estagiodocencia',
            name='relatorio_entregue',
        ),
        migrations.AlterField(
            model_name='estagiodocencia',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('AGUARD_CIENCIA', 'Aguardando Ciente do Orientador'), ('AGUARD_ASSINATURA', 'Aguardando Aprovação da Coordenação'), ('ANALISE_DISP', 'Em Análise de Dispensa'), ('DISPENSADO', 'Dispensado'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARD_RELAT', 'Aguardando Relatório'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=25),
        ),
        migrations.AlterField(
            model_name='estagiodocencia',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Supervisor'),
        ),
    ]
