# Generated by Django 5.2 on 2026-06-06 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0030_alter_processo_status_alter_processo_status_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('SETOR', 'Setor'), ('COMISSAO', 'Comissao')], default='SETOR', max_length=20),
        ),
        migrations.CreateModel(
            name='SetorMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=django.utils.timezone.localdate)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('designado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designacoes_setor', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='processos.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_setor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setor__nome', 'usuario__nome', '-data_entrada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_saida__isnull', True)), fields=('setor', 'usuario'), name='unique_membro_ativo_por_setor')],
            },
        ),
    ]
