# Generated by Django 5.2 on 2026-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0030_remove_estagiodocencia_dispensado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Deposito versao final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificacao'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso'), ('TRAJETORIA', 'Trajetoria academica'), ('ESTAGIO_DOCENCIA', 'Estagio docencia')], max_length=25),
        ),
    ]
