# Generated by Django 5.2 on 2026-06-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0031_setor_tipo_setormembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_defesa', models.CharField(choices=[('DEFESA_MESTRADO', 'Defesa de Mestrado'), ('QUALIFICACAO_DOUTORADO', 'Qualificação de Doutorado'), ('DEFESA_DOUTORADO', 'Defesa de Doutorado')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chave', models.CharField(blank=True, max_length=255)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('horario_previsto', models.TimeField(blank=True, null=True)),
                ('modalidade_local_link', models.TextField(blank=True)),
                ('requisitos_cumpridos', models.BooleanField(default=False)),
                ('justificativa_excepcionalidade', models.TextField(blank=True)),
                ('ciencia_recomendacao_mpf', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada')], default='RASCUNHO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_banca', to='processos.aluno')),
                ('docente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'DOCENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_banca_docente', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_banca_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_banca', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MembroBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('EXAMINADOR_EXTERNO', 'Examinador externo'), ('EXAMINADOR_EXTERNO_1', 'Examinador externo 1'), ('EXAMINADOR_EXTERNO_2', 'Examinador externo 2'), ('EXAMINADOR_INTERNO', 'Examinador interno'), ('TERCEIRO_EXAMINADOR', 'Terceiro examinador'), ('QUARTO_EXAMINADOR', 'Quarto examinador'), ('SUPLENTE', 'Suplente'), ('SUPLENTE_EXTERNO', 'Suplente externo'), ('SUPLENTE_INTERNO', 'Suplente interno')], max_length=30)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='processos.solicitacaobanca')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('solicitacao', 'papel'), name='unique_membro_por_papel_solicitacao')],
            },
        ),
    ]
