# Generated by Django 5.2 on 2026-06-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0032_solicitacaobanca_membrobanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaobanca',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_banca_anexadas', to='processos.processo'),
        ),
    ]
