# Generated by Django 5.2 on 2026-06-12 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0033_solicitacaobanca_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaTrajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('nome', models.CharField(max_length=255)),
                ('semestre', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Informe no formato YYYY.1 ou YYYY.2.', regex='^\\d{4}\\.[12]$')])),
                ('conceito', models.CharField(blank=True, max_length=20)),
                ('creditos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carga_horaria', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('TRANCADA', 'Trancada')], default='CURSANDO', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['semestre', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoTrajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ARTIGO_PERIODICO', 'Artigo em periodico'), ('ARTIGO_EVENTO', 'Artigo em evento'), ('LIVRO_CAPITULO', 'Livro/capitulo'), ('OUTRO', 'Outro')], default='ARTIGO_PERIODICO', max_length=25)),
                ('autores', models.TextField(blank=True)),
                ('veiculo', models.CharField(blank=True, max_length=255)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('doi_url', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes_trajetoria_criadas', to=settings.AUTH_USER_MODEL)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['-ano', 'titulo'],
            },
        ),
    ]
