# Generated by Django 5.2 on 2026-06-12 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0034_disciplinatrajetoria_publicacaotrajetoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaambiente',
            name='excluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='excluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_ambiente_excluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='justificativa_exclusao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('EXCLUIDA', 'Excluida')], default='ATIVA', max_length=12),
        ),
    ]
