# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0035_reservaambiente_excluida_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajetoriaacademica",
            name="nivel_curso",
            field=models.CharField(
                choices=[
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                    ("POSDOUTORADO", "Posdoutorado"),
                    ("ALUNO_ESPECIAL", "Aluno especial"),
                ],
                max_length=20,
            ),
        ),
    ]
