# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0036_alter_trajetoriaacademica_nivel_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="status_aluno",
            field=models.CharField(
                choices=[
                    ("EM_AVALIACAO", "Em avaliacao"),
                    ("ATIVO", "Ativo"),
                    ("DESLIGADO", "Desligado"),
                    ("DEFENDEU", "Defendeu"),
                ],
                default="ATIVO",
                max_length=12,
            ),
        ),
    ]
