# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0037_aluno_status_em_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trajetoriaacademica",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_HOMOLOGACAO", "Em homologacao"),
                    ("ATIVA", "Ativa"),
                    ("CONCLUIDA", "Concluida"),
                    ("DESLIGADA", "Desligada"),
                    ("TRANCADA", "Trancado"),
                    ("REMOVIDA", "Removida"),
                ],
                default="ATIVA",
                max_length=15,
            ),
        ),
    ]
