# Generated by Codex on 2026-06-30

from django.db import migrations


def ativar_alunos_em_avaliacao(apps, schema_editor):
    Aluno = apps.get_model("processos", "Aluno")
    Aluno.objects.filter(status_aluno="EM_AVALIACAO").update(is_active=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0038_trajetoria_status_homologacao_removida"),
    ]

    operations = [
        migrations.RunPython(ativar_alunos_em_avaliacao, noop),
    ]
