# Generated by Codex on 2026-06-30

from django.contrib.auth.hashers import make_password
from django.db import migrations


DOCENTES_PPGEC = [
    ("Alexandre Magno Andrade Maciel", "alexandre.maciel@upe.br", "Professor Permanente", "POLI"),
    ("Bruno Costa e Silva Nogueira", "bruno@ic.ufal.br", "Professor colaborador", "Externo"),
    ("Bruno Jose Torres Fernandes", "bruno.fernandes@upe.br", "Professor Permanente", "POLI"),
    ("Byron Leite Dantas Bezerra", "byron.leite@upe.br", "Professor Permanente", "POLI"),
    ("Carlo Marcelo Revoredo da Silva", "marcelo.revoredo@upe.br", "Professor Permanente", "POLI"),
    ("Carlos Alexandre Silva de Melo", "carlos.melo@upe.br", "Professor Permanente", "Garanhuns"),
    ("Carmelo Jose Albanez Bastos Filho", "carmelo.filho@upe.br", "Professor Permanente", "POLI"),
    ("Cleyton Mario de Oliveira Rodrigues", "cleyton.rodrigues@upe.br", "Professor Permanente", "POLI"),
    ("Daniel Augusto Ribeiro Chaves", "daniel.rchaves@upe.br", "Professor Permanente", "POLI"),
    ("Denis Silva da Silveira", "denis@ecomp.poli.br", "Professor colaborador", "Externo"),
    ("Diego Jose Rativa Millan", "diego.rativa@upe.br", "Professor Permanente", "POLI"),
    ("Diego Marconi Pinheiro Ferreira Silva", "dmpfs@ecomp.poli.br", "Professor colaborador", "Externo"),
    ("Dimas Cassimiro do Nascimento Filho", "dimas.cassimiro@ufape.edu.br", "Professor colaborador", "Externo"),
    ("Domingos Savio de Oliveira Santos Junior", "domingos.santos@upe.br", "Professor Permanente", "Caruaru"),
    ("Elyda Laisa Soares Xavier Freitas", "elyda.freitas@upe.br", "Professor Permanente", "UPE Caruaru"),
    ("Eraylson Galdino da Silva", "eraylson.galdino@upe.br", "Professor Permanente", "Garanhuns"),
    ("Fernanda Maria Ribeiro de Alencar", "fernanda.mralencar@upe.br", "Professor Permanente", "Externo"),
    ("Fernando Buarque de Lima Neto", "fbln@dsc.upe.br", "Professor Permanente", "POLI"),
    ("Gustavo Rau de Almeida Callou", "gustavo.callou@upe.br", "Professor colaborador", "Externo"),
    ("Hemir da Cunha Santiago", "hemir.santiago@upe.br", "Professor colaborador", "POLI"),
    ("Ivaldir Honorio de Farias Junior", "ivaldir.farias@upe.br", "Professor Permanente", "Garanhuns"),
    ("Jackson Raniel Florencio da Silva", "jackson.florencio@upe.br", "Professor Colaborador", "Garanhuns"),
    ("Joao Fausto Lorenzato de Oliveira", "fausto.lorenzato@upe.br", "Professor Permanente", "POLI"),
    ("Jose Paulo Goncalves de Oliveira", "jpgo@ecomp.poli.br", "Professor colaborador", "POLI"),
    ("Leandro Honorato de Souza Silva", "leandro.ssilva@upe.br", "Professor Permanente", "POLI"),
    ("Liliane Sheyla da Silva Fonseca", "liliane.ssilva@upe.br", "Professor Permanente", "POLI"),
    ("Maicon Herverton Lino Ferreira da Silva Barros", "maicon.herverton@upe.br", "Professor Permanente", "Caruaru"),
    ("Maria Lencastre Pinheiro de Menezes e Cruz", "maria@dsc.upe.br", "Professor Permanente", "POLI"),
    ("Mariana Maia Peixoto", "mariana.peixoto@upe.br", "Professor Permanente", "Garanhuns"),
    ("Pablo Vinicius Alves de Barros", "pablo.viniciusab@upe.br", "Professor colaborador", "Externo"),
    ("Patricia Takako Endo", "patricia.endo@upe.br", "Professor Permanente", "Caruaru"),
    ("Raphael Augusto de Sousa Dourado", "raphael.dourado@upe.br", "Professor Permanente", "Caruaru"),
    ("Roberta Andrade de Araujo Fagundes", "roberta.fagundes@upe.br", "Professor Permanente", "POLI"),
    ("Sergio Murilo Maciel Fernandes", "sergio.fernandes@upe.br", "Professor Permanente", "POLI"),
    ("Sidney Marlon Lopes de Lima", "sidney.lima@upe.br", "Professor Permanente", "Externo"),
    ("Wellington Pinheiro dos Santos", "wellington.santos@upe.br", "Professor Permanente", "Externo"),
    ("Wylliams Barbosa Santos", "wbs@upe.br", "Professor Permanente", "POLI"),
]


def cadastrar_docentes_ppgec(apps, schema_editor):
    User = apps.get_model("processos", "User")
    Docente = apps.get_model("processos", "Docente")
    unusable_password = make_password(None)

    for nome, email, cargo, campus in DOCENTES_PPGEC:
        email = email.strip().lower()
        permanente = "permanente" in cargo.lower()
        externo = campus.strip().lower() == "externo"
        docente = Docente.objects.filter(email__iexact=email).first()

        if docente:
            docente.nome = nome
            docente.tipo_usuario = "DOCENTE"
            docente.is_active = True
            docente.is_staff = False
            docente.is_superuser = False
            docente.permanente = permanente
            docente.externo = externo
            docente.save()
            continue

        user = User.objects.filter(email__iexact=email).first()
        if user:
            user.nome = nome
            user.tipo_usuario = "DOCENTE"
            user.is_active = True
            user.is_staff = False
            user.is_superuser = False
            user.save()
            Docente.objects.create(
                user_ptr_id=user.pk,
                permanente=permanente,
                externo=externo,
                coordenador=False,
            )
            continue

        Docente.objects.create(
            nome=nome,
            email=email,
            password=unusable_password,
            tipo_usuario="DOCENTE",
            is_active=True,
            is_staff=False,
            is_superuser=False,
            permanente=permanente,
            externo=externo,
            coordenador=False,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0039_aluno_em_avaliacao_is_active"),
    ]

    operations = [
        migrations.RunPython(cadastrar_docentes_ppgec, noop),
    ]
