# Generated by Django 5.2 on 2026-07-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0040_seed_docentes_ppgec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Deposito versao final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificacao'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso'), ('TRAJETORIA', 'Trajetoria academica'), ('ESTAGIO_DOCENCIA', 'Estagio docencia')], max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('APROVEITAMENTO_DISPENSA_CREDITOS', 'Aproveitamento de Créditos ou Dispensa de Disciplina'), ('DEFESA_MESTRADO', 'Defesa de Mestrado'), ('DEFESA_DOUTORADO', 'Defesa de Doutorado'), ('QUALIFICACAO_DOUTORADO', 'Qualificação de Doutorado'), ('ESTAGIO_DOCENCIA', 'Estágio docência'), ('TRANCAMENTO_MATRICULA', 'Trancamento de Matrícula'), ('PRORROGACAO_PRAZO', 'Prorrogação de Prazo'), ('REINGRESSO', 'Reingresso'), ('MUDANCA_ORIENTADOR', 'Mudança de Orientador(a)'), ('OUTRO', 'Outro')], max_length=40),
        ),
        migrations.CreateModel(
            name='EstagioDocencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=255, verbose_name='Nome do Supervisor')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('AGUARD_CIENCIA', 'Aguardando Ciente do Orientador'), ('AGUARD_ASSINATURA', 'Aguardando Aprovação da Coordenação'), ('ANALISE_DISP', 'Em Análise de Dispensa'), ('DISPENSADO', 'Dispensado'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARD_RELAT', 'Aguardando Relatório'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=25)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('processo_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagio_gerado', to='processos.processo')),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios_docencia', to='processos.trajetoriaacademica')),
            ],
            options={
                'verbose_name': 'Estágio de Docência',
                'verbose_name_plural': 'Estágios de Docência',
                'ordering': ['id'],
            },
        ),
    ]
