# Generated by Django 5.2 on 2026-07-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0040_seed_docentes_ppgec'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_tipo', models.CharField(choices=[('DOCENTE', 'Docente'), ('SETOR', 'Setor/Comissao')], max_length=12)),
                ('tipo_documento', models.CharField(choices=[('DOCUMENTO_SEI', 'Documento SEI'), ('BLOCO_SEI', 'Bloco de assinatura SEI'), ('PDF', 'PDF para assinatura eletronica')], max_length=20)),
                ('numero_documento_sei', models.CharField(blank=True, max_length=80)),
                ('numero_bloco_sei', models.CharField(blank=True, max_length=80)),
                ('documento_pdf', models.FileField(blank=True, upload_to='assinaturas/originais/%Y/%m/')),
                ('documento_assinado_pdf', models.FileField(blank=True, upload_to='assinaturas/assinados/%Y/%m/')),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_assinatura', models.TextField(blank=True)),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_assinatura_atendidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_assinatura_criadas', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_assinatura_docente', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_assinatura', to='processos.setor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
