# Generated by Django 5.2 on 2026-07-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0041_alter_alteracaoaluno_tipo_alter_processo_tipo_and_more"),
        ("processos", "0041_solicitacaoassinatura"),
    ]

    operations = []
