# Generated by Django 5.2 on 2026-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0045_periodo_datas_aulas_presenciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='pre_requisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
