# Generated by Django 5.2 on 2026-07-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0051_aluno_sexo_polos_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitacaomatricula',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Matrícula solicitada'), ('HOMOLOGADO', 'Matrícula solicitada'), ('EM_LISTA_ESPERA', 'Matrícula solicitada - em lista de espera'), ('INDEFERIDO', 'Indeferido'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SOLICITADA', 'Solicitada'), ('PARCIALMENTE_HOMOLOGADA', 'Parcialmente processada'), ('HOMOLOGADA', 'Processada'), ('INDEFERIDA', 'Indeferida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=25),
        ),
    ]
