# Generated by Django 5.2 on 2026-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0052_alter_itemsolicitacaomatricula_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertadisciplina',
            options={'ordering': ['periodo__nome', 'disciplina__nome', 'docente_responsavel__nome']},
        ),
        migrations.RemoveConstraint(
            model_name='ofertadisciplina',
            name='unique_oferta_disciplina_periodo',
        ),
        migrations.AddConstraint(
            model_name='ofertadisciplina',
            constraint=models.UniqueConstraint(fields=('periodo', 'disciplina', 'docente_responsavel'), name='unique_oferta_disciplina_periodo_docente'),
        ),
    ]
