# Generated by Django 5.2 on 2026-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0053_alter_ofertadisciplina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='genero',
            field=models.CharField(blank=True, choices=[('MULHER', 'Mulher'), ('HOMEM', 'Homem'), ('NAO_BINARIO', 'Não binário'), ('OUTRO', 'Outro'), ('NAO_INFORMAR', 'Prefiro não informar')], max_length=15),
        ),
    ]
