# Generated by Django 5.2 on 2026-07-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0055_concluir_trajetorias_aluno_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificacao'), ('HORAS_COMPLEMENTARES', 'Horas complementares'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Depósito versão final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificação'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso'), ('TRAJETORIA', 'Trajetória acadêmica'), ('ESTAGIO_DOCENCIA', 'Estágio docência')], max_length=25),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo_atribuido_nascimento',
            field=models.CharField(blank=True, choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('NAO_INFORMAR', 'Prefiro não informar')], max_length=15),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('EM_AVALIACAO', 'Em avaliação'), ('ATIVO', 'Ativo'), ('DESLIGADO', 'Desligado'), ('DEFENDEU', 'Defendeu')], default='ATIVO', max_length=12),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciência'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], default='EM_ANALISE', max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status_inicial',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciência'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='trajetoriaacademica',
            name='status',
            field=models.CharField(choices=[('EM_HOMOLOGACAO', 'Em homologação'), ('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluida'), ('DESLIGADA', 'Desligada'), ('TRANCADA', 'Trancado'), ('REMOVIDA', 'Removida')], default='ATIVA', max_length=15),
        ),
        migrations.AlterField(
            model_name='tramitacaoprocesso',
            name='status_resultante',
            field=models.CharField(blank=True, choices=[('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DOCUMENTO', 'Aguardando documento'), ('AGUARDANDO_CIENCIA', 'Aguardando ciência'), ('EM_DEBATE', 'Em debate'), ('FINALIZADO', 'Finalizado')], max_length=25, null=True),
        ),
    ]
