# Generated by Django 5.2 on 2026-07-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0057_normaliza_tipo_aproveitamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteracaoaluno',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Status'), ('QUALIFICACAO', 'Qualificação'), ('HORAS_COMPLEMENTARES', 'Horas complementares'), ('DEFESA', 'Defesa'), ('DEPOSITO_FINAL', 'Depósito versão final'), ('PRAZO_QUALIFICACAO', 'Prazo qualificação'), ('PRAZO_DEFESA', 'Prazo defesa'), ('ORIENTADOR', 'Orientador'), ('COORIENTADOR', 'Coorientador'), ('REINGRESSO', 'Reingresso'), ('TRAJETORIA', 'Trajetória acadêmica'), ('ESTAGIO_DOCENCIA', 'Estágio docência')], max_length=25),
        ),
        migrations.AlterField(
            model_name='disponibilidadesala',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='trajetoriaacademica',
            name='status',
            field=models.CharField(choices=[('EM_HOMOLOGACAO', 'Em homologação'), ('ATIVA', 'Ativa'), ('CONCLUIDA', 'Concluída'), ('DESLIGADA', 'Desligada'), ('TRANCADA', 'Trancado'), ('REMOVIDA', 'Removida')], default='ATIVA', max_length=15),
        ),
    ]
