# Generated by Django 5.2 on 2026-07-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0058_alter_alteracaoaluno_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='disciplinatrajetoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='disciplinatrajetoria',
            name='situacao',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('TRANCADA', 'Trancada')], default='CURSANDO', max_length=15, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='grupolimitehorascomplementares',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lancamentohorascomplementares',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='membrobanca',
            name='instituicao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='normahorascomplementares',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ofertadisciplina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='processos.periodoletivo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='polo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='publicacaotrajetoria',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solicitacaoassinatura',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='solicitacaobanca',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_matricula', to='processos.periodoletivo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='tipoatividadehorascomplementares',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tramitacaoprocesso',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
