# Generated by Django 5.2 on 2026-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0064_alter_trajetoria_nivel_pos_doutorado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulapresencialoferta',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='disponibilidadesala',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='encontrooferta',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='lancamentohorascomplementares',
            name='periodo_realizacao',
            field=models.CharField(blank=True, max_length=120, verbose_name='Período de realização'),
        ),
        migrations.AlterField(
            model_name='lancamentohorascomplementares',
            name='referencia_decisao',
            field=models.TextField(blank=True, verbose_name='Referência da decisão'),
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início do período letivo'),
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='matricula_fim',
            field=models.DateField(verbose_name='Fim da matrícula'),
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='matricula_inicio',
            field=models.DateField(verbose_name='Início da matrícula'),
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='modificacao_fim',
            field=models.DateField(verbose_name='Fim da modificação'),
        ),
        migrations.AlterField(
            model_name='periodoletivo',
            name='modificacao_inicio',
            field=models.DateField(verbose_name='Início da modificação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoassinatura',
            name='numero_bloco_sei',
            field=models.CharField(blank=True, max_length=80, verbose_name='Número do bloco de assinatura no SEI'),
        ),
        migrations.AlterField(
            model_name='solicitacaoassinatura',
            name='numero_documento_sei',
            field=models.CharField(blank=True, max_length=80, verbose_name='Número do documento no SEI'),
        ),
        migrations.AlterField(
            model_name='solicitacaoassinatura',
            name='observacao_assinatura',
            field=models.TextField(blank=True, verbose_name='Observação da assinatura'),
        ),
    ]
