# Generated by Django 5.2 on 2026-08-07 18:24

import django.db.models.deletion
import processos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0066_rotulos_com_acento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoDeVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=processos.models.caminho_da_declaracao_de_vinculo, verbose_name='Arquivo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes_de_vinculo', to='processos.aluno', verbose_name='Aluno')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaracoes_de_vinculo_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaracoes_de_vinculo', to='processos.periodoletivo', verbose_name='Período letivo')),
            ],
            options={
                'verbose_name': 'Declaração de vínculo',
                'verbose_name_plural': 'Declarações de vínculo',
                'ordering': ['-periodo__nome', 'aluno__nome'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'periodo'), name='declaracao_vinculo_unica_por_periodo')],
            },
        ),
    ]
