# Generated by Django 5.2 on 2026-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0068_declaracaodevinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('DOCENTE', 'Docente'), ('SERVIDOR', 'Servidor'), ('BOLSISTA_VOLUNTARIO', 'Bolsista/Voluntário')], default='SERVIDOR', max_length=20),
        ),
    ]
