# Generated by Django 5.2 on 2026-08-18 17:59

import django.db.models.deletion
import django.utils.timezone
from datetime import date
from django.conf import settings
from django.db import migrations, models


def preencher_datas_ingresso(apps, schema_editor):
    TrajetoriaAcademica = apps.get_model("processos", "TrajetoriaAcademica")
    datas = {
        "2022.2": date(2022, 8, 1),
        "2023.2": date(2023, 10, 1),
        "2024.1": date(2024, 4, 1),
        "2024.2": date(2024, 8, 1),
        "2025.1": date(2025, 2, 1),
        "2025.2": date(2025, 8, 1),
        "2026.1": date(2026, 3, 1),
        "2026.2": date(2026, 8, 1),
    }
    for semestre, data_ingresso in datas.items():
        TrajetoriaAcademica.objects.filter(ingresso=semestre, data_ingresso__isnull=True).update(
            data_ingresso=data_ingresso
        )


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0070_alteracaomatricula_item_fase_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetoriaacademica',
            name='data_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Data de ingresso'),
        ),
        migrations.RunPython(preencher_datas_ingresso, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProrrogacaoTrajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveSmallIntegerField()),
                ('data_concessao', models.DateField(default=django.utils.timezone.localdate)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogacoes', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['data_concessao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrancamentoTrajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trancamentos', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['data_inicio', 'id'],
            },
        ),
    ]
