# Generated by Django 5.2 on 2026-08-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0071_trajetoriaacademica_data_ingresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetoriaacademica',
            name='data_limite_qualificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data limite do projeto de dissertação'),
        ),
        migrations.CreateModel(
            name='ApresentacaoQualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.PositiveSmallIntegerField(default=1)),
                ('data_apresentacao', models.DateField()),
                ('conceito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_qualificacao', to='processos.trajetoriaacademica')),
            ],
            options={
                'ordering': ['tentativa'],
                'constraints': [models.UniqueConstraint(fields=('trajetoria', 'tentativa'), name='qualificacao_tentativa_unica')],
            },
        ),
    ]
