# Generated by Django 5.2 on 2026-08-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0074_processo_aluno_interessado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('SETOR', 'Setor'), ('COMISSAO', 'Comissao'), ('ESTRATEGICO', 'Planejamento Estratégico')], default='SETOR', max_length=20),
        ),
        migrations.CreateModel(
            name='MetaPlanejamentoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=120)),
                ('fragilidade', models.TextField(blank=True, verbose_name='Fragilidade')),
                ('indicador', models.TextField(blank=True, verbose_name='Indicador')),
                ('periodo_vigente', models.CharField(choices=[('Planejamento 2025', '2025')], default='Planejamento 2025', max_length=20, verbose_name='Período vigente')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_planejamento_estrategico', to='processos.setor')),
            ],
            options={
                'ordering': ['periodo_vigente', 'categoria'],
            },
        ),
    ]
