# Generated by Django 5.2 on 2026-08-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0075_alter_setor_tipo_metaplanejamentoestrategico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcoesPlanejamentoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, verbose_name='Ação')),
                ('status', models.CharField(choices=[('Não iniciada', 'Não iniciada'), ('Em andamento', 'Em andamento'), ('Concluída parcialmente', 'Concluída parcialmente'), ('Concluída totalmente', 'Concluída totalmente'), ('Cancelada', 'Cancelada')], default='Não iniciada', max_length=30, verbose_name='Status')),
                ('data_inicio_planejado', models.DateField(blank=True, null=True, verbose_name='Data inicio planejada')),
                ('data_termino_planejado', models.DateField(blank=True, null=True, verbose_name='Data término planejada')),
                ('resultados_esperados', models.TextField(blank=True, verbose_name='Resultados esperados')),
                ('data_inicio_executado', models.DateField(blank=True, null=True, verbose_name='Data inicio executada')),
                ('data_termino_executado', models.DateField(blank=True, null=True, verbose_name='Data término executada')),
                ('resultados_atingidos', models.TextField(blank=True, verbose_name='Resultados atingidos')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('meta_planejamento_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_planejamento_estrategico', to='processos.metaplanejamentoestrategico')),
            ],
            options={
                'ordering': ['meta_planejamento_estrategico', 'acao'],
            },
        ),
    ]
