# Generated by Django 5.2 on 2026-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0076_acoesplanejamentoestrategico'),
        ('processos', '0080_multiplos_ambientes_aula_presencial'),
    ]

    operations = [
    ]
